spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource: # jpa와 같은 라인으로 한 칸 앞으로 당겨야 합니다.
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2: # jpa와 같은 라인으로 한 칸 앞으로 당겨야 합니다.
    console:
      enabled: true # enable이 아니라 enabled입니다! ⭐